set_property SRC_FILE_INFO {cfile:/storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/constrs_1/new/system.xdc rfile:../../../pfs_ctrlr.srcs/constrs_1/new/system.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/constrs_1/new/timing.xdc rfile:../../../pfs_ctrlr.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F20 [ get_ports pfs_rst_nxt\[0\]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E20 [ get_ports pfs_rst_nxt\[3\]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B22 [ get_ports pfs_rst_nxt\[1\]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A22 [ get_ports pfs_rst_nxt\[4\]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A18 [ get_ports pfs_rst_nxt\[2\]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D12 [ get_ports pfs_rst_nxt\[5\]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E11 [ get_ports pfs_cmd_nxt\[0\]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E15 [ get_ports pfs_cmd_nxt\[3\]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G30 [ get_ports pfs_cmd_nxt\[1\]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C30 [ get_ports pfs_cmd_nxt\[4\]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F21 [ get_ports pfs_cmd_nxt\[2\]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C19 [ get_ports pfs_cmd_nxt\[5\]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E14 [ get_ports pfs_clk_nxt\[0\]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H30 [ get_ports pfs_clk_nxt\[3\]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D29 [ get_ports pfs_clk_nxt\[1\]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B28 [ get_ports pfs_clk_nxt\[4\]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E21 [ get_ports pfs_clk_nxt\[2\]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B19 [ get_ports pfs_clk_nxt\[5\]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H14 [ get_ports pfs_resp_nxt\[0\]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G14 [ get_ports pfs_resp_nxt\[3\]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F15 [ get_ports pfs_resp_nxt\[1\]]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E16 [ get_ports pfs_resp_nxt\[4\]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F12 [ get_ports pfs_resp_nxt\[2\]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E13 [ get_ports pfs_resp_nxt\[5\]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L16 [ get_ports pfs_rclk_nxt\[0\]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K16 [ get_ports pfs_rclk_nxt\[3\]]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L15 [ get_ports pfs_rclk_nxt\[1\]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K15 [ get_ports pfs_rclk_nxt\[4\]]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K13 [ get_ports pfs_rclk_nxt\[2\]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J13 [ get_ports pfs_rclk_nxt\[5\]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D26 [ get_ports pfs_psu_en\[0\]]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C26 [ get_ports pfs_psu_en\[3\]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G29 [ get_ports pfs_psu_en\[1\]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F30 [ get_ports pfs_psu_en\[4\]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B30 [ get_ports pfs_psu_en\[2\]]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A30 [ get_ports pfs_psu_en\[5\]]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [ get_ports pfs_rx_err\[0\]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [ get_ports pfs_rx_err\[1\]]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [ get_ports pfs_rx_err\[2\]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [ get_ports pfs_rx_err\[3\]]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE26 [ get_ports pfs_rx_err\[4\]]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [ get_ports pfs_rx_err\[5\]]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/serializer/tx_cnt_reg[*]/C}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/rd_data_reg[*]/D}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins block_design_i/pfs_daughtercard_0/inst/counter_roll_reg/*] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/counter_roll_z_reg[0]/D}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/tx_fifo/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_36_bl.fifo_36_bl/RDCLK}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/status_reg_reg[*]/D}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/proc_sys_reset_0/U0/ACTIVE_LOW_PR_OUT_DFF[0].peripheral_aresetn_reg[0]/C}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/rst_pipe_reg[0]/S}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/proc_sys_reset_0/U0/ACTIVE_LOW_PR_OUT_DFF[0].peripheral_aresetn_reg[0]/C}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/rst_pipe_reg[0]/D}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/ser_rst_reg/C}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/tx_fifo/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_36_bl.fifo_36_bl/RST}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/ctrl_reg_reg[0]/C}] -to [get_pins {block_design_i/pfs_daughtercard_0/inst/genblk1[*].i_pfs_sector/rst_pipe_reg[0]/D}]
