#!/bin/bash -f
# Vivado (TM) v2017.2 (64-bit)
#
# Filename    : block_design.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Sep 06 18:20:25 PDT 2017
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017 
#
# usage: block_design.sh [-help]
# usage: block_design.sh [-lib_map_path]
# usage: block_design.sh [-noclean_files]
# usage: block_design.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'block_design.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_3 axi_lite_ipif_v3_0_4 mdm_v3_2_10 lib_cdc_v1_0_2 proc_sys_reset_v5_0_11 lib_pkg_v1_0_2 axi_timer_v2_0_15 axi_intc_v4_1_10 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_12 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_11 xlconcat_v2_1_1 fifo_generator_v13_1_4 lib_bmg_v1_0_8 axi_ethernet_buffer_v2_0_15 xbip_utils_v3_0_7 xbip_pipe_v3_0_3 xbip_bram18k_v3_0_3 mult_gen_v12_0_12 tri_mode_ethernet_mac_v9_0_8 c_reg_fd_v12_0_3 c_mux_bit_v12_0_3 c_shift_ram_v12_0_10 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_3 xbip_addsub_v3_0_3 c_addsub_v12_0_10 c_gate_bit_v12_0_3 xbip_counter_v3_0_3 c_counter_binary_v12_0_10 xlconstant_v1_1_3 util_vector_logic_v2_0_1 lib_fifo_v1_0_8 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_15 axi_sg_v4_1_6 axi_dma_v7_1_14 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_13 axi_data_fifo_v2_1_12 axi_crossbar_v2_1_14 axi_uartlite_v2_0_17 smartconnect_v1_0 axi_protocol_converter_v2_1_13 axi_clock_converter_v2_1_12 axi_dwidth_converter_v2_1_13)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "block_design.sh - Script generated by export_simulation (Vivado v2017.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "/tools/xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/xilinx/Vivado/2017.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/fe06/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_microblaze_0_0/sim/block_design_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_10 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/5967/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_mdm_0_0/sim/block_design_mdm_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_top.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_state.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_common.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_mc.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_col_mach.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_select.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_common.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_top.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/block_design_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/rtl/block_design_mig_7series_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_11 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_rst_mig_7series_0_200M_0/sim/block_design_rst_mig_7series_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_15 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/a004/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_timer_0_0/sim/block_design_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/d685/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_intc_0_0/sim/block_design_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/162e/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_dlmb_v10_0/sim/block_design_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/block_design/ip/block_design_ilmb_v10_0/sim/block_design_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_12 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/51e1/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_dlmb_bram_if_cntlr_0/sim/block_design_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/block_design/ip/block_design_ilmb_bram_if_cntlr_0/sim/block_design_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_lmb_bram_0/sim/block_design_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_proc_sys_reset_0_1/sim/block_design_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_0_11 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9183/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_bram_ctrl_0_0/sim/block_design_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_blk_mem_gen_0_0/sim/block_design_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/73b7/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_xlconcat_0_0/sim/block_design_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_8 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/0dfc/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernet_buffer_v2_0_15 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9ee4/hdl/axi_ethernet_buffer_v2_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_0/sim/bd_f793_eth_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/3d01/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7db8/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/403d/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f0ab/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work tri_mode_ethernet_mac_v9_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/4f1d/hdl/tri_mode_ethernet_mac_v9_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work tri_mode_ethernet_mac_v9_0_8 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/4f1d/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/common/bd_f793_mac_0_block_reset_sync.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/common/bd_f793_mac_0_block_sync_block.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_axi4_lite_ipif_top.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_axi4_lite_ipif_wrapper.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/physical/bd_f793_mac_0_gmii_if.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_tx_clk_gen.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/statistics/bd_f793_mac_0_vector_decode.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_block.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_support.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_support_resets.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/e1e2/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f2d7/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/5ac0/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_2/sim/bd_f793_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/1e87/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/c9c4/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/2957/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/a394/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/b6ab/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/de69/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/d6cf/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_3/sim/bd_f793_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/45df/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_4/sim/bd_f793_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/25ee/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_5/sim/bd_f793_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/hdl/bd_f793.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_ethernet_0_0/sim/block_design_axi_ethernet_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_8 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/c387/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_15 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/43a6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_6 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/ddc9/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_14 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/bb0b/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_dma_0_0/sim/block_design_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_xbar_1/sim/block_design_xbar_1.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_clk_wiz_0_0/block_design_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_clk_wiz_0_0/block_design_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_clk_wiz_1_0/block_design_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_clk_wiz_1_0/block_design_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_uartlite_v2_0_17 $vhdlan_opts \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/1b8b/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_axi_uartlite_0_0/sim/block_design_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ipshared/b0e5/deserialize.sv" \
    "$ref_dir/../../../bd/block_design/ipshared/b0e5/fifo.sv" \
    "$ref_dir/../../../bd/block_design/ipshared/b0e5/pfs_sector.sv" \
    "$ref_dir/../../../bd/block_design/ipshared/b0e5/serialize.sv" \
    "$ref_dir/../../../bd/block_design/ipshared/b0e5/pfs_daughtercard.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_pfs_daughtercard_0_0/sim/block_design_pfs_daughtercard_0_0.sv" \
    "$ref_dir/../../../bd/block_design/ipshared/fe20/simple_ip.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_simple_ip_0_0/sim/block_design_simple_ip_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/e870/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_20/sim/bd_ed65_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/224a/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_26/sim/bd_ed65_m00s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_33/sim/bd_ed65_m01s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_40/sim/bd_ed65_m02s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_47/sim/bd_ed65_m03s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_54/sim/bd_ed65_m04s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_61/sim/bd_ed65_m05s2a_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_68/sim/bd_ed65_m06s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/986a/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_74/sim/bd_ed65_m06e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_69/sim/bd_ed65_m06arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_70/sim/bd_ed65_m06rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_71/sim/bd_ed65_m06awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_72/sim/bd_ed65_m06wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_73/sim/bd_ed65_m06bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_67/sim/bd_ed65_m05e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_62/sim/bd_ed65_m05arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_63/sim/bd_ed65_m05rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_64/sim/bd_ed65_m05awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_65/sim/bd_ed65_m05wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_66/sim/bd_ed65_m05bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_60/sim/bd_ed65_m04e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_55/sim/bd_ed65_m04arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_56/sim/bd_ed65_m04rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_57/sim/bd_ed65_m04awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_58/sim/bd_ed65_m04wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_59/sim/bd_ed65_m04bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_53/sim/bd_ed65_m03e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_48/sim/bd_ed65_m03arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_49/sim/bd_ed65_m03rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_50/sim/bd_ed65_m03awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_51/sim/bd_ed65_m03wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_52/sim/bd_ed65_m03bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_46/sim/bd_ed65_m02e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_41/sim/bd_ed65_m02arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_42/sim/bd_ed65_m02rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_43/sim/bd_ed65_m02awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_44/sim/bd_ed65_m02wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_45/sim/bd_ed65_m02bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_39/sim/bd_ed65_m01e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_34/sim/bd_ed65_m01arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_35/sim/bd_ed65_m01rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_36/sim/bd_ed65_m01awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_37/sim/bd_ed65_m01wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_38/sim/bd_ed65_m01bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_32/sim/bd_ed65_m00e_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_27/sim/bd_ed65_m00arn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_28/sim/bd_ed65_m00rn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_29/sim/bd_ed65_m00awn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_30/sim/bd_ed65_m00wn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_31/sim/bd_ed65_m00bn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_21/sim/bd_ed65_sarn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_22/sim/bd_ed65_srn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_23/sim/bd_ed65_sawn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_24/sim/bd_ed65_swn_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_25/sim/bd_ed65_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/5300/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_17/sim/bd_ed65_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/cbcb/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_18/sim/bd_ed65_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/cc66/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_19/sim/bd_ed65_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7daf/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_2/sim/bd_ed65_arinsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_3/sim/bd_ed65_rinsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_4/sim/bd_ed65_awinsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_5/sim/bd_ed65_winsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_6/sim/bd_ed65_binsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_7/sim/bd_ed65_aroutsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_8/sim/bd_ed65_routsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_9/sim/bd_ed65_awoutsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_10/sim/bd_ed65_woutsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_11/sim/bd_ed65_boutsw_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_12/sim/bd_ed65_arni_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_13/sim/bd_ed65_rni_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_14/sim/bd_ed65_awni_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_15/sim/bd_ed65_wni_0.sv" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_16/sim/bd_ed65_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_0/sim/bd_ed65_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/ip/ip_1/sim/bd_ed65_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/bd_0/hdl/bd_ed65.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_smartconnect_0_1/sim/block_design_smartconnect_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/80fd/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/3bde/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/9c7f" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../pfs_ctrlr.srcs/sources_1/bd/block_design/ipshared/f80f/hdl/verilog" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_ds_0/sim/block_design_auto_ds_0.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_cc_0/sim/block_design_auto_cc_0.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_us_4/sim/block_design_auto_us_4.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_us_3/sim/block_design_auto_us_3.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_us_2/sim/block_design_auto_us_2.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_us_1/sim/block_design_auto_us_1.v" \
    "$ref_dir/../../../bd/block_design/ip/block_design_auto_us_0/sim/block_design_auto_us_0.v" \
    "$ref_dir/../../../bd/block_design/hdl/block_design.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.block_design xil_defaultlib.glbl -o block_design_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./block_design_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./block_design.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key block_design_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc block_design_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./block_design.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: block_design.sh [-help]\n\
Usage: block_design.sh [-lib_map_path]\n\
Usage: block_design.sh [-reset_run]\n\
Usage: block_design.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
