# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_f793_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_f793_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
