# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/block_design_axi_ethernet_0_0.xci
# IP: The module: 'block_design_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/bd_f793.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793 || ORIG_REF_NAME==bd_f793}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_0/bd_f793_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_eth_buf_0 || ORIG_REF_NAME==bd_f793_eth_buf_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/bd_f793_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_mac_0 || ORIG_REF_NAME==bd_f793_mac_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_2/bd_f793_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_c_shift_ram_0_0 || ORIG_REF_NAME==bd_f793_c_shift_ram_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_3/bd_f793_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_c_counter_binary_0_0 || ORIG_REF_NAME==bd_f793_c_counter_binary_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_4/bd_f793_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_xlconstant_0_0 || ORIG_REF_NAME==bd_f793_xlconstant_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_5/bd_f793_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_util_vector_logic_0_0 || ORIG_REF_NAME==bd_f793_util_vector_logic_0_0}]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/bd_f793_ooc.xdc

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/block_design_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/synth/block_design_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/block_design_axi_ethernet_0_0.xci
# IP: The module: 'block_design_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/bd_f793.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793 || ORIG_REF_NAME==bd_f793}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_0/bd_f793_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_eth_buf_0 || ORIG_REF_NAME==bd_f793_eth_buf_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_1/bd_f793_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_mac_0 || ORIG_REF_NAME==bd_f793_mac_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_2/bd_f793_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_c_shift_ram_0_0 || ORIG_REF_NAME==bd_f793_c_shift_ram_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_3/bd_f793_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_c_counter_binary_0_0 || ORIG_REF_NAME==bd_f793_c_counter_binary_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_4/bd_f793_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_xlconstant_0_0 || ORIG_REF_NAME==bd_f793_xlconstant_0_0}]

# IP: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/ip/ip_5/bd_f793_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f793_util_vector_logic_0_0 || ORIG_REF_NAME==bd_f793_util_vector_logic_0_0}]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/bd_0/bd_f793_ooc.xdc

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/block_design_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /storage/syncthing/work/pfs_ctrlr/pfs_ctrlr.srcs/sources_1/bd/block_design/ip/block_design_axi_ethernet_0_0/synth/block_design_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
