# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# XDC: new/timing.xdc

# Block Designs: bd/block_design/block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design}]

# IP: bd/block_design/ip/block_design_microblaze_0_0/block_design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_microblaze_0_0 || ORIG_REF_NAME==block_design_microblaze_0_0}]

# IP: bd/block_design/ip/block_design_mdm_0_0/block_design_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_mdm_0_0 || ORIG_REF_NAME==block_design_mdm_0_0}]

# IP: bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_mig_7series_0_0 || ORIG_REF_NAME==block_design_mig_7series_0_0}]

# IP: bd/block_design/ip/block_design_rst_mig_7series_0_200M_0/block_design_rst_mig_7series_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==block_design_rst_mig_7series_0_200M_0}]

# IP: bd/block_design/ip/block_design_axi_timer_0_0/block_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_timer_0_0 || ORIG_REF_NAME==block_design_axi_timer_0_0}]

# IP: bd/block_design/ip/block_design_axi_intc_0_0/block_design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_intc_0_0 || ORIG_REF_NAME==block_design_axi_intc_0_0}]

# IP: bd/block_design/ip/block_design_dlmb_v10_0/block_design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_dlmb_v10_0 || ORIG_REF_NAME==block_design_dlmb_v10_0}]

# IP: bd/block_design/ip/block_design_ilmb_v10_0/block_design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ilmb_v10_0 || ORIG_REF_NAME==block_design_ilmb_v10_0}]

# IP: bd/block_design/ip/block_design_dlmb_bram_if_cntlr_0/block_design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==block_design_dlmb_bram_if_cntlr_0}]

# IP: bd/block_design/ip/block_design_ilmb_bram_if_cntlr_0/block_design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==block_design_ilmb_bram_if_cntlr_0}]

# IP: bd/block_design/ip/block_design_lmb_bram_0/block_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_lmb_bram_0 || ORIG_REF_NAME==block_design_lmb_bram_0}]

# IP: bd/block_design/ip/block_design_proc_sys_reset_0_1/block_design_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_proc_sys_reset_0_1 || ORIG_REF_NAME==block_design_proc_sys_reset_0_1}]

# IP: bd/block_design/ip/block_design_axi_bram_ctrl_0_0/block_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==block_design_axi_bram_ctrl_0_0}]

# IP: bd/block_design/ip/block_design_blk_mem_gen_0_0/block_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_blk_mem_gen_0_0 || ORIG_REF_NAME==block_design_blk_mem_gen_0_0}]

# IP: bd/block_design/ip/block_design_xlconcat_0_0/block_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_xlconcat_0_0 || ORIG_REF_NAME==block_design_xlconcat_0_0}]

# IP: bd/block_design/ip/block_design_axi_ethernet_0_0/block_design_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_ethernet_0_0 || ORIG_REF_NAME==block_design_axi_ethernet_0_0}]

# IP: bd/block_design/ip/block_design_axi_dma_0_0/block_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_dma_0_0 || ORIG_REF_NAME==block_design_axi_dma_0_0}]

# IP: bd/block_design/ip/block_design_axi_interconnect_1_0/block_design_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_interconnect_1_0 || ORIG_REF_NAME==block_design_axi_interconnect_1_0}]

# IP: bd/block_design/ip/block_design_xbar_1/block_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_xbar_1 || ORIG_REF_NAME==block_design_xbar_1}]

# IP: bd/block_design/ip/block_design_clk_wiz_0_0/block_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_clk_wiz_0_0 || ORIG_REF_NAME==block_design_clk_wiz_0_0}]

# IP: bd/block_design/ip/block_design_clk_wiz_1_0/block_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_clk_wiz_1_0 || ORIG_REF_NAME==block_design_clk_wiz_1_0}]

# IP: bd/block_design/ip/block_design_axi_uartlite_0_0/block_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_uartlite_0_0 || ORIG_REF_NAME==block_design_axi_uartlite_0_0}]

# IP: bd/block_design/ip/block_design_pfs_daughtercard_0_0/block_design_pfs_daughtercard_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_pfs_daughtercard_0_0 || ORIG_REF_NAME==block_design_pfs_daughtercard_0_0}]

# IP: bd/block_design/ip/block_design_simple_ip_0_0/block_design_simple_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_simple_ip_0_0 || ORIG_REF_NAME==block_design_simple_ip_0_0}]

# IP: bd/block_design/ip/block_design_smartconnect_0_1/block_design_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_smartconnect_0_1 || ORIG_REF_NAME==block_design_smartconnect_0_1}]

# IP: bd/block_design/ip/block_design_auto_ds_0/block_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_ds_0 || ORIG_REF_NAME==block_design_auto_ds_0}]

# IP: bd/block_design/ip/block_design_auto_cc_0/block_design_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_cc_0 || ORIG_REF_NAME==block_design_auto_cc_0}]

# IP: bd/block_design/ip/block_design_auto_us_4/block_design_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_us_4 || ORIG_REF_NAME==block_design_auto_us_4}]

# IP: bd/block_design/ip/block_design_auto_us_3/block_design_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_us_3 || ORIG_REF_NAME==block_design_auto_us_3}]

# IP: bd/block_design/ip/block_design_auto_us_2/block_design_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_us_2 || ORIG_REF_NAME==block_design_auto_us_2}]

# IP: bd/block_design/ip/block_design_auto_us_1/block_design_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_us_1 || ORIG_REF_NAME==block_design_auto_us_1}]

# IP: bd/block_design/ip/block_design_auto_us_0/block_design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_us_0 || ORIG_REF_NAME==block_design_auto_us_0}]

# XDC: bd/block_design/block_design_ooc.xdc
